In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('play_tennis.csv')

In [4]:
df.drop(columns=['day'],inplace=True)

In [5]:
df.head(14)

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [5]:
#Problem 1 

#Outlook=S , Temp=Hot , Humidity=H , Wind=W
#Play or no play?

In [6]:
#Solution

#P(Yes | S,Hot,H,W) = P(S | Y) *  P(Hot | Y) *  P(H | Y) *  P(W | Y) * P(Y) 
#P(No | S,Hot,H,W) = P(S | N) *  P(Hot | N) *  P(H | N) *  P(W | N) * P(N)

#Compart the probability using the maximum a posteriori rule

In [7]:
#Now if the problem changes then we need find the probability according to that say this
# Outlook=Overcast , Temp=C , Humidity=L , Wind=W

In [8]:
#Training 
#naive bayes in this step store all the probabilities it calculates in the dictionary form
#Test
#then in this it directly goes there and search there

In [9]:
#calculate this
#P(YES)
#P(NO)

In [10]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [11]:
py=9/14
pn=5/14

In [12]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [15]:
#Outlook

pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [16]:
pon=0  #probability of outlook overcast when no
prn=2/5
psn=3/5

poy=4/9
pry=3/9
psy=2/9

In [18]:
#Temperature

pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [19]:
pcooln=1/5
photn=2/5
pmildn=2/5

pcooly=3/9
photy=2/9
pmildy=4/9

In [21]:
#Humidity

pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [22]:
phighn=4/5
pnormn=1/5

phighy=3/9
pnormy=6/9

In [24]:
#Wind

pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [25]:
pstrn=3/5
pweakn=2/5

pstrony=3/9
pweaky=6/9

In [26]:
 #Outlook=S , Temp=Hot , Humidity=H , Wind=W
#Play or no play?

Pyes = py*psy*photy*phighy*pweaky
Pno = pn*psn*photn*phighn*pweakn

In [27]:
print(Pyes)
print(Pno)

0.007054673721340388
0.02742857142857143

In [106]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder
from sklearn.naive_bayes import CategoricalNB
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import BernoulliNB

In [107]:
X = df.drop('play', axis=1)
y = df['play']

In [108]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=12)

In [109]:
encoder = OrdinalEncoder()
X_train = encoder.fit_transform(X_train)
X_test = encoder.transform(X_test)

In [110]:
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [111]:
y_train

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1])

In [112]:
X_train

array([[1., 0., 1., 0.],
       [2., 2., 1., 0.],
       [2., 1., 0., 1.],
       [1., 0., 1., 1.],
       [2., 0., 1., 1.],
       [1., 2., 0., 1.],
       [0., 1., 0., 1.],
       [2., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 2., 0., 0.],
       [0., 2., 0., 0.]])

In [113]:
nb = CategoricalNB()

In [114]:
nb.fit(X_train, y_train)

CategoricalNB()

In [115]:
y_pred = nb.predict(X_test)

In [116]:
y_pred

array([1, 1, 1])

In [117]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.6666666666666666

In [118]:
#The question

In [119]:
new_data = pd.DataFrame({
    'outlook': ['Sunny'],
    'temp': ['Hot'],
    'humidity': ['High'],
    'wind': ['Weak']
})

In [120]:
new_data_encoded = encoder.transform(new_data)

In [121]:
prediction = nb.predict(new_data_encoded)

In [122]:
prediction_label = le.inverse_transform(prediction)

In [123]:
print("Prediction:", prediction_label)

Prediction: ['No']